# Generated by Django 3.2 on 2023-06-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAula', models.CharField(max_length=200)),
                ('nombreProfesor', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='fecha de registro')),
            ],
        ),
    ]
