# Generated by Django 4.1.7 on 2023-06-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aula_dispositivo_persona_rol_tipoaula_zona_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleAccesos',
            new_name='DetalleAcceso',
        ),
    ]
